# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Testing vars
      run: echo ${{ secrets.SERVER }}
     
    - name: Testing dir
      run: ls ./
     
    - name: Deploy
      uses: BoatNg/funny-deploy@v1.0.3
      env:
        REMOTE_HOST: ${{ secrets.SERVER }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        REMOTE_PASSWORD: ${{ secrets.PASSWORD }}
        REMOTE_PORT: ${{ secrets.PORT }}
        SOURCE: ./
        REMOTE_PATH: ${{ secrets.TARGET }}

    - name: Restart backend service
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        password: ${{ secrets.PASSWORD }}
        command: echo test > ~/test.txt

    # Runs a single command using the runners shell
    #- name: Run a one-line script
    #  run: echo Hello, world!

    # Runs a set of commands using the runners shell
    #- name: Run a multi-line script
    #  run: |
    #    echo Add other actions to build,
    #    echo test, and deploy your project.
